# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from symbolic_reasoning import engine_pb2 as symbolic__reasoning_dot_engine__pb2


class SimulationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScenarioList = channel.unary_unary(
                '/proto.SimulationService/GetScenarioList',
                request_serializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.GetScenarioListResponse.FromString,
                )
        self.LoadScenarioByFilePath = channel.unary_unary(
                '/proto.SimulationService/LoadScenarioByFilePath',
                request_serializer=symbolic__reasoning_dot_engine__pb2.LoadScenarioRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ScenInfo.FromString,
                )
        self.StartScenario = channel.unary_unary(
                '/proto.SimulationService/StartScenario',
                request_serializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.PauseScenario = channel.unary_unary(
                '/proto.SimulationService/PauseScenario',
                request_serializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.EndScenario = channel.unary_unary(
                '/proto.SimulationService/EndScenario',
                request_serializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.ReDeduction = channel.unary_unary(
                '/proto.SimulationService/ReDeduction',
                request_serializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.SetTimeCompress = channel.unary_unary(
                '/proto.SimulationService/SetTimeCompress',
                request_serializer=symbolic__reasoning_dot_engine__pb2.SetTimeCompressRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.SetSimStep = channel.unary_unary(
                '/proto.SimulationService/SetSimStep',
                request_serializer=symbolic__reasoning_dot_engine__pb2.SetSimStepRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.GetEngineStatus = channel.unary_unary(
                '/proto.SimulationService/GetEngineStatus',
                request_serializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EngineStatusResponse.FromString,
                )
        self.GetThreeSituation = channel.unary_unary(
                '/proto.SimulationService/GetThreeSituation',
                request_serializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationResponse.FromString,
                )
        self.SubscribeThreeSituation = channel.unary_stream(
                '/proto.SimulationService/SubscribeThreeSituation',
                request_serializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationResponse.FromString,
                )
        self.UnsubscribeThreeSituation = channel.unary_unary(
                '/proto.SimulationService/UnsubscribeThreeSituation',
                request_serializer=symbolic__reasoning_dot_engine__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.GetUnitData = channel.unary_unary(
                '/proto.SimulationService/GetUnitData',
                request_serializer=symbolic__reasoning_dot_engine__pb2.GetUnitDataRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.GetUnitDataResponse.FromString,
                )
        self.SetUnitData = channel.unary_unary(
                '/proto.SimulationService/SetUnitData',
                request_serializer=symbolic__reasoning_dot_engine__pb2.SetUnitDataRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.GetWeaponFiringInfo = channel.unary_unary(
                '/proto.SimulationService/GetWeaponFiringInfo',
                request_serializer=symbolic__reasoning_dot_engine__pb2.GetWeaponFiringInfoRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.GetWeaponFiringInfoResponse.FromString,
                )
        self.AttackTarget = channel.unary_unary(
                '/proto.SimulationService/AttackTarget',
                request_serializer=symbolic__reasoning_dot_engine__pb2.AttackTargetRequest.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
                )
        self.startDedicew = channel.unary_unary(
                '/proto.SimulationService/startDedicew',
                request_serializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.pauseDedicew = channel.unary_unary(
                '/proto.SimulationService/pauseDedicew',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.getTimeCompression = channel.unary_unary(
                '/proto.SimulationService/getTimeCompression',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.TimeCompression.FromString,
                )
        self.getEndSignal = channel.unary_unary(
                '/proto.SimulationService/getEndSignal',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.EndSignalw.FromString,
                )
        self.getSituation = channel.unary_unary(
                '/proto.SimulationService/getSituation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.SituationDatas.FromString,
                )
        self.getUseUpReportw = channel.unary_unary(
                '/proto.SimulationService/getUseUpReportw',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.UseUpReports.FromString,
                )
        self.getAttackReport = channel.unary_unary(
                '/proto.SimulationService/getAttackReport',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.AttackReports.FromString,
                )
        self.getDetectionReport = channel.unary_unary(
                '/proto.SimulationService/getDetectionReport',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.DetectionReports.FromString,
                )
        self.getCombatArea = channel.unary_unary(
                '/proto.SimulationService/getCombatArea',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.AreaPointList.FromString,
                )
        self.getMissionList = channel.unary_unary(
                '/proto.SimulationService/getMissionList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.MissionList.FromString,
                )
        self.aircraftTakeOffSinglew = channel.unary_unary(
                '/proto.SimulationService/aircraftTakeOffSinglew',
                request_serializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.aircraftReturnToBasew = channel.unary_unary(
                '/proto.SimulationService/aircraftReturnToBasew',
                request_serializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.setUnitRoutew = channel.unary_unary(
                '/proto.SimulationService/setUnitRoutew',
                request_serializer=symbolic__reasoning_dot_engine__pb2.UnitRoutew.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.adjustUnitAltitudeAndSpeed = channel.unary_unary(
                '/proto.SimulationService/adjustUnitAltitudeAndSpeed',
                request_serializer=symbolic__reasoning_dot_engine__pb2.UnitAltitudeAndSpeedw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.attackContactw = channel.unary_unary(
                '/proto.SimulationService/attackContactw',
                request_serializer=symbolic__reasoning_dot_engine__pb2.AttackRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.attackOrientationw = channel.unary_unary(
                '/proto.SimulationService/attackOrientationw',
                request_serializer=symbolic__reasoning_dot_engine__pb2.AttackOrientationw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.controlUnitSensorw = channel.unary_unary(
                '/proto.SimulationService/controlUnitSensorw',
                request_serializer=symbolic__reasoning_dot_engine__pb2.SensorControlRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.delpoySonobuoyw = channel.unary_unary(
                '/proto.SimulationService/delpoySonobuoyw',
                request_serializer=symbolic__reasoning_dot_engine__pb2.SonobuoyDelpoyRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )
        self.cancelAttackw = channel.unary_unary(
                '/proto.SimulationService/cancelAttackw',
                request_serializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
                response_deserializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
                )


class SimulationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetScenarioList(self, request, context):
        """获取想定列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadScenarioByFilePath(self, request, context):
        """加载想定
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScenario(self, request, context):
        """开始/继续运行想定
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseScenario(self, request, context):
        """暂停想定
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndScenario(self, request, context):
        """结束想定
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReDeduction(self, request, context):
        """重新推演
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeCompress(self, request, context):
        """设置倍速
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSimStep(self, request, context):
        """设置仿真步长
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineStatus(self, request, context):
        """获取引擎运行状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreeSituation(self, request, context):
        """获取单帧态势数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeThreeSituation(self, request, context):
        """订阅持续推送态势数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeThreeSituation(self, request, context):
        """取消订阅持续推送态势数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnitData(self, request, context):
        """获取单位数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUnitData(self, request, context):
        """修改单位数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeaponFiringInfo(self, request, context):
        """获取武器发射信息（根据我方单位ID和敌方单位ID）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttackTarget(self, request, context):
        """手动武器分配攻击（指定武器和数量攻击目标）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startDedicew(self, request, context):
        """=================================== WHU 需要的protocol ======================================
        开始推演
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pauseDedicew(self, request, context):
        """暂停推演
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTimeCompression(self, request, context):
        """获取时间压缩（倍速）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getEndSignal(self, request, context):
        """获取推演结束信号
        如果结束了就返回true，如果没有结束就返回false
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSituation(self, request, context):
        """态势获取与战报获取方法
        获取态势数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUseUpReportw(self, request, context):
        """获取使用/损耗战损报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAttackReport(self, request, context):
        """获取攻击/战损报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDetectionReport(self, request, context):
        """获取侦察/探测报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCombatArea(self, request, context):
        """获取作参考点/参考区域
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMissionList(self, request, context):
        """获取任务列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def aircraftTakeOffSinglew(self, request, context):
        """智能体动作执行与指控接口的8类方法（9个）
        飞机单机起飞
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def aircraftReturnToBasew(self, request, context):
        """飞机返航至基地
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setUnitRoutew(self, request, context):
        """设置实体机动航路
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def adjustUnitAltitudeAndSpeed(self, request, context):
        """设置实体机动海拔高度和速度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def attackContactw(self, request, context):
        """打击目标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def attackOrientationw(self, request, context):
        """纯方位攻击
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def controlUnitSensorw(self, request, context):
        """传感器控制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delpoySonobuoyw(self, request, context):
        """部署声纳浮标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancelAttackw(self, request, context):
        """放弃打击
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScenarioList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScenarioList,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.GetScenarioListResponse.SerializeToString,
            ),
            'LoadScenarioByFilePath': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadScenarioByFilePath,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.LoadScenarioRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ScenInfo.SerializeToString,
            ),
            'StartScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScenario,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'PauseScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseScenario,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'EndScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.EndScenario,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'ReDeduction': grpc.unary_unary_rpc_method_handler(
                    servicer.ReDeduction,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'SetTimeCompress': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeCompress,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.SetTimeCompressRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'SetSimStep': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSimStep,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.SetSimStepRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'GetEngineStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineStatus,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.EmptyRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EngineStatusResponse.SerializeToString,
            ),
            'GetThreeSituation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreeSituation,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationResponse.SerializeToString,
            ),
            'SubscribeThreeSituation': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeThreeSituation,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ThreeSituationResponse.SerializeToString,
            ),
            'UnsubscribeThreeSituation': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeThreeSituation,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.UnsubscribeRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'GetUnitData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnitData,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.GetUnitDataRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.GetUnitDataResponse.SerializeToString,
            ),
            'SetUnitData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUnitData,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.SetUnitDataRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'GetWeaponFiringInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeaponFiringInfo,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.GetWeaponFiringInfoRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.GetWeaponFiringInfoResponse.SerializeToString,
            ),
            'AttackTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.AttackTarget,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.AttackTargetRequest.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EmptyResponse.SerializeToString,
            ),
            'startDedicew': grpc.unary_unary_rpc_method_handler(
                    servicer.startDedicew,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'pauseDedicew': grpc.unary_unary_rpc_method_handler(
                    servicer.pauseDedicew,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'getTimeCompression': grpc.unary_unary_rpc_method_handler(
                    servicer.getTimeCompression,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.TimeCompression.SerializeToString,
            ),
            'getEndSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.getEndSignal,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.EndSignalw.SerializeToString,
            ),
            'getSituation': grpc.unary_unary_rpc_method_handler(
                    servicer.getSituation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.SituationDatas.SerializeToString,
            ),
            'getUseUpReportw': grpc.unary_unary_rpc_method_handler(
                    servicer.getUseUpReportw,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.UseUpReports.SerializeToString,
            ),
            'getAttackReport': grpc.unary_unary_rpc_method_handler(
                    servicer.getAttackReport,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.AttackReports.SerializeToString,
            ),
            'getDetectionReport': grpc.unary_unary_rpc_method_handler(
                    servicer.getDetectionReport,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.DetectionReports.SerializeToString,
            ),
            'getCombatArea': grpc.unary_unary_rpc_method_handler(
                    servicer.getCombatArea,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.AreaPointList.SerializeToString,
            ),
            'getMissionList': grpc.unary_unary_rpc_method_handler(
                    servicer.getMissionList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.MissionList.SerializeToString,
            ),
            'aircraftTakeOffSinglew': grpc.unary_unary_rpc_method_handler(
                    servicer.aircraftTakeOffSinglew,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'aircraftReturnToBasew': grpc.unary_unary_rpc_method_handler(
                    servicer.aircraftReturnToBasew,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'setUnitRoutew': grpc.unary_unary_rpc_method_handler(
                    servicer.setUnitRoutew,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.UnitRoutew.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'adjustUnitAltitudeAndSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.adjustUnitAltitudeAndSpeed,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.UnitAltitudeAndSpeedw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'attackContactw': grpc.unary_unary_rpc_method_handler(
                    servicer.attackContactw,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.AttackRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'attackOrientationw': grpc.unary_unary_rpc_method_handler(
                    servicer.attackOrientationw,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.AttackOrientationw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'controlUnitSensorw': grpc.unary_unary_rpc_method_handler(
                    servicer.controlUnitSensorw,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.SensorControlRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'delpoySonobuoyw': grpc.unary_unary_rpc_method_handler(
                    servicer.delpoySonobuoyw,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.SonobuoyDelpoyRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
            'cancelAttackw': grpc.unary_unary_rpc_method_handler(
                    servicer.cancelAttackw,
                    request_deserializer=symbolic__reasoning_dot_engine__pb2.IdRequestw.FromString,
                    response_serializer=symbolic__reasoning_dot_engine__pb2.ResponseDataw.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetScenarioList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/GetScenarioList',
            symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.GetScenarioListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadScenarioByFilePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/LoadScenarioByFilePath',
            symbolic__reasoning_dot_engine__pb2.LoadScenarioRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ScenInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/StartScenario',
            symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PauseScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/PauseScenario',
            symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/EndScenario',
            symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReDeduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/ReDeduction',
            symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimeCompress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/SetTimeCompress',
            symbolic__reasoning_dot_engine__pb2.SetTimeCompressRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSimStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/SetSimStep',
            symbolic__reasoning_dot_engine__pb2.SetSimStepRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEngineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/GetEngineStatus',
            symbolic__reasoning_dot_engine__pb2.EmptyRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EngineStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetThreeSituation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/GetThreeSituation',
            symbolic__reasoning_dot_engine__pb2.ThreeSituationRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ThreeSituationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeThreeSituation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.SimulationService/SubscribeThreeSituation',
            symbolic__reasoning_dot_engine__pb2.ThreeSituationRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ThreeSituationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnsubscribeThreeSituation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/UnsubscribeThreeSituation',
            symbolic__reasoning_dot_engine__pb2.UnsubscribeRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/GetUnitData',
            symbolic__reasoning_dot_engine__pb2.GetUnitDataRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.GetUnitDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUnitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/SetUnitData',
            symbolic__reasoning_dot_engine__pb2.SetUnitDataRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWeaponFiringInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/GetWeaponFiringInfo',
            symbolic__reasoning_dot_engine__pb2.GetWeaponFiringInfoRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.GetWeaponFiringInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AttackTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/AttackTarget',
            symbolic__reasoning_dot_engine__pb2.AttackTargetRequest.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startDedicew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/startDedicew',
            symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pauseDedicew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/pauseDedicew',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTimeCompression(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getTimeCompression',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.TimeCompression.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getEndSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getEndSignal',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.EndSignalw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getSituation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getSituation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.SituationDatas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUseUpReportw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getUseUpReportw',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.UseUpReports.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAttackReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getAttackReport',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.AttackReports.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDetectionReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getDetectionReport',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.DetectionReports.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCombatArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getCombatArea',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.AreaPointList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMissionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/getMissionList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.MissionList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def aircraftTakeOffSinglew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/aircraftTakeOffSinglew',
            symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def aircraftReturnToBasew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/aircraftReturnToBasew',
            symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setUnitRoutew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/setUnitRoutew',
            symbolic__reasoning_dot_engine__pb2.UnitRoutew.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def adjustUnitAltitudeAndSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/adjustUnitAltitudeAndSpeed',
            symbolic__reasoning_dot_engine__pb2.UnitAltitudeAndSpeedw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def attackContactw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/attackContactw',
            symbolic__reasoning_dot_engine__pb2.AttackRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def attackOrientationw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/attackOrientationw',
            symbolic__reasoning_dot_engine__pb2.AttackOrientationw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def controlUnitSensorw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/controlUnitSensorw',
            symbolic__reasoning_dot_engine__pb2.SensorControlRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delpoySonobuoyw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/delpoySonobuoyw',
            symbolic__reasoning_dot_engine__pb2.SonobuoyDelpoyRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def cancelAttackw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SimulationService/cancelAttackw',
            symbolic__reasoning_dot_engine__pb2.IdRequestw.SerializeToString,
            symbolic__reasoning_dot_engine__pb2.ResponseDataw.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
